# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-traileraddict}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Gough"]
  s.date = %q{2010-05-26}
  s.description = %q{A simple API wrapper for TrailerAddict.com}
  s.email = %q{aaron@aarongough.com}
  s.extra_rdoc_files = [
    "MIT-LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ruby-traileraddict.rb",
     "lib/ruby-traileraddict/traileraddict.rb",
     "test/fixtures/api_response.txt",
     "test/fixtures/example_com.txt",
     "test/fixtures/search.txt",
     "test/setup/test_unit_extensions.rb",
     "test/setup/url_mocks.rb",
     "test/test_helper.rb",
     "test/unit/trailer_addict_test.rb"
  ]
  s.homepage = %q{https://github.com/aarongough/ruby-traileraddict}
  s.rdoc_options = ["--charset=UTF-8", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple API wrapper for TrailerAddict.com}
  s.test_files = [
    "test/setup/test_unit_extensions.rb",
     "test/setup/url_mocks.rb",
     "test/test_helper.rb",
     "test/unit/trailer_addict_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<hpricot>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

